---
name: 'Terraform and TFLint PR Commenter'
description: 'Adds opinionated comments to a PR from Terraform fmt/init/plan/validate/tflint output'
author: 'GetTerminus'
branding:
  icon: 'git-pull-request'
  color: 'blue'
inputs:
  commenter_type:
    description: 'The type of comment. Options: [fmt, init, plan, validate, tflint]'
    required: true
  commenter_input:
    description: 'The comment to post from a previous step output. This must be trimmed to at least 128 KiB. Required for non plan commenter types.'
    required: false
  commenter_plan_path:
    description: 'The tfplan file. Required if commenter input is not set for plan commenter types.'
    required: false
  commenter_exitcode:
    description: 'The exit code from a previous step output'
    required: true
  multiple_modules:
    description: 'Support multiple modules (do not cut off after first plan)'
    required: false
    default: 'false'
  terraform_version:
    description: 'The version of terraform from the workflow.'
    required: false
    default: '1.4.6'
runs:
  using: "composite"
  steps:
    - name: Set Terraform Version if inputs.terraform_version is Empty  # Until https://github.com/actions/runner/issues/924 is fixed
      id: tf_version
      run: |
        if [[ -z ${{ inputs.terraform_version }} ]]; then
          echo "version=1.4.6" >> $GITHUB_OUTPUT
        else
          echo "version=${{ inputs.terraform_version }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Build commenter docker image
      run: docker build --build-arg TERRAFORM_VERSION=${{ steps.tf_version.outputs.version }} -t commenter https://github.com/VerticeOne/terraform-pr-commenter.git#fix/CE-108_terragrunt
      shell: bash
    - name: Run commenter image (plan)
      if: ${{ inputs.commenter_type == 'plan' }}
      env:
        COMMENTER_INPUT: ${{ inputs.commenter_input }}
        COMMENTER_MULTIPLE_MODULES: ${{ inputs.multiple_modules }}
        COMMENTER_PLAN_FILE: ${{ inputs.commenter_plan_path }}
        GITHUB_EVENT: ${{ toJSON(github.event) }}
      run: |
        docker run \
        -e GITHUB_TOKEN \
        -e TF_WORKSPACE \
        -e EXPAND_SUMMARY_DETAILS \
        -e HIGHLIGHT_CHANGES \
        -e GITHUB_EVENT \
        -e COMMENTER_INPUT \
        -e COMMENTER_DEBUG \
        -e COMMENTER_ECHO \
        -e COMMENTER_MULTIPLE_PLANS \
        -e COMMENTER_PLAN_FILE \
        -e COMMENTER_POST_PLAN_OUTPUTS \
        -v "$(pwd)"/:/workspace \
        commenter ${{ inputs.commenter_type }} ${{ inputs.commenter_exitcode }}
      shell: bash
    - name: Run commenter image (non-plan)
      if: ${{ inputs.commenter_type != 'plan' }}
      env:
        COMMENTER_INPUT: ${{ inputs.commenter_input }}
        GITHUB_EVENT: ${{ toJSON(github.event) }}
      run: |
        docker run \
        -e GITHUB_TOKEN \
        -e TF_WORKSPACE \
        -e EXPAND_SUMMARY_DETAILS \
        -e HIGHLIGHT_CHANGES \
        -e GITHUB_EVENT \
        -e COMMENTER_INPUT \
        -e COMMENTER_DEBUG \
        -e COMMENTER_ECHO \
        commenter ${{ inputs.commenter_type }} ${{ inputs.commenter_exitcode }}
      shell: bash
