name: 'Terraform and TFLint PR Commenter'
description: 'Adds opinionated comments to a PR from Terraform fmt/init/plan/validate/tflint output'
author: 'Rob Burger'
branding:
  icon: 'git-pull-request'
  color: 'blue'
inputs:
  commenter_type:
    description: 'The type of comment. Options: [fmt, init, plan, validate, tflint]'
    required: true
  commenter_input:
    description: 'The comment to post from a previous step output. This must be trimmed to at least 128 KiB. Required for non plan commenter types.'
    required: false
  commenter_plan_path:
    description: 'The tfplan file. Required if commenter input is not set for plan commenter types.'
    required: false
  commenter_exitcode:
    description: 'The exit code from a previous step output'
    required: true
  terraform_version:
    description: 'The version of terraform from the workflow.'
    required: false
    default: "1.4.6"
  use_beta_version:
    description: 'Whether to use the beta version of the commenter'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Build commenter docker image (master)
      if: ${{ inputs.use_beta_version != 'true' }}
      run: docker build --build-arg TERRAFORM_VERSION=${{ inputs.terraform_version }} -t commenter https://github.com/GetTerminus/terraform-pr-commenter.git#master
      shell: bash
    - name: Build commenter docker image (beta)
      if: ${{ inputs.use_beta_version == 'true' }}
      # append branch with a pound (#) if developing.  e.g., `commenter.git#my-branch`
      run: docker build --build-arg TERRAFORM_VERSION=${{ inputs.terraform_version }} -t commenter https://github.com/GetTerminus/terraform-pr-commenter.git#v2.2.0
      shell: bash
    - name: Run commenter image (plan)
      if: ${{ inputs.commenter_type == 'plan' }}
      env:
        COMMENTER_INPUT: ${{ inputs.commenter_input }}
        COMMENTER_PLAN_FILE: ${{ inputs.commenter_plan_path }}
        GITHUB_EVENT: ${{ toJSON(github.event) }}
      run: |
        docker run \
        -e GITHUB_TOKEN \
        -e TF_WORKSPACE \
        -e EXPAND_SUMMARY_DETAILS \
        -e HIGHLIGHT_CHANGES \
        -e GITHUB_EVENT \
        -e COMMENTER_INPUT \
        -e COMMENTER_DEBUG \
        -e COMMENTER_ECHO \
        -e COMMENTER_PLAN_FILE \
        -e COMMENTER_POST_PLAN_OUTPUTS \
        -v "$(pwd)"/:/workspace \
        commenter ${{ inputs.commenter_type }} ${{ inputs.commenter_exitcode }}
      shell: bash
    - name: Run commenter image (non-plan)
      if: ${{ inputs.commenter_type != 'plan' }}
      env:
        COMMENTER_INPUT: ${{ inputs.commenter_input }}
        GITHUB_EVENT: ${{ toJSON(github.event) }}
      run: |
        docker run \
        -e GITHUB_TOKEN \
        -e TF_WORKSPACE \
        -e EXPAND_SUMMARY_DETAILS \
        -e HIGHLIGHT_CHANGES \
        -e GITHUB_EVENT \
        -e COMMENTER_INPUT \
        -e COMMENTER_DEBUG \
        -e COMMENTER_ECHO \
        commenter ${{ inputs.commenter_type }} ${{ inputs.commenter_exitcode }}
      shell: bash
