name: Release

on:
  push:
    branches: [master]

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "master"
      - uses: sersoft-gmbh/running-release-tags-action@v2
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          github-token: ${{secrets.GITHUB_TOKEN}}
