name: Vulnerability Scan

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  vulnerability-scan:
    name: Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run Vulnerability Scan
        uses: GetTerminus/terminus-github-actions/ci-vulnerability-scans@v2